### ISSUE TITLE
How to use System.Console in PascalABC?

### ISSUE THREAD

**Issue by pakLebah** [pascalabcnet/pascalabcnet#2309]
Hi... a new user here. FYI, I'm not a russian and I don't speak russian either. So, please reply it in english (or indonesian if you could).

I'd like to use CRT unit in PascalABC. But I found some problems.

1. If I use CRT unit, the IDE refuses to debug my program and forces me to run it without IDE (shift+F9). But if I did it, the compiled program raises runtime error such as this image below.  Though I could click 'Continue', it's still annoying. And the most important thing is I couldn't debug my code.

![Cuplikan layar 2020-09-19 185443](https://user-images.githubusercontent.com/11470932/93667001-c8e52200-faac-11ea-8eeb-1f574403e0d5.png)

2. I found an old issue thread saying we should not use CRT unit because it's a legacy unit and use the System.Console unit instead. But if I put the unit in the `uses` section, the IDE complains that it's unable to find the `System.Console` namespace. If CRT unit is just a wrapper of Console namespace, then why the IDE is unable to debug it?

So, if I use the CRT unit then I can't do debugging, but I can't use the Console namespace either. What should I do?

I'm using PascalABC v.3.7.1 (the latest version as I write this issue) on Windows 10.

Thank you.

**Comment by SunSerega** [comment]
`Console` is a class, not unit. Write `Console` on empty line and press `.` (dot), IDE will show you list of available methods.
Though you still wouldn't be able to `Console.Clear` when starting from IDE, because there isn't any console window to clear.
My suggestion would be to use:
```
// space before $ to cancel it for now
{ $define UseConsole}
...
{$ifdef UseConsole}
Console.Clear;
{$endif UseConsole}
```

And btw, it's generally advised to use [forum](http://forum.mmcs.sfedu.ru/c/pascalabcnet/10) for questions and issues for reporting bugs. issues are more of a direct line to devs, while on forum there are more people to hear you.

**Comment by pakLebah** [comment]
Thank you for answering my question. Any call to Console's methods is always producing runtime exception saying 'the handle is invalid'. So, how to initiate a console window and use to it as Console's output?

Oh, I didn't know there's a forum. I didn't found any link to it in PascalABC's web site (the english one). Thank you for the info, I'll join the forum soon.

**Comment by SunSerega** [comment]
> 'the handle is invalid'

This means you don't have console window. As i said, things that change console window, like `Console.Clear`, would still require you to start in Shift+F9 mode (or by executing .exe file).

> any link to it in PascalABC's web site (the english one)

I hope you mean this one?
http://pascalabc.net/en/
The fact that you call it PascalABC confuses me, because it's a different language.

But yeah, it's english version of that site is pretty restricted, there are many things missing.
In you switch language to Russian - you'll see "Форум" button on bottom of left panel.
