### ISSUE TITLE
How to use P/Invoke in PascalABC.NET?

### ISSUE THREAD

**Issue by 3oheicrw** [pascalabcnet/pascalabcnet#2621]
I wanted to load a native DLL from PascalABC.NET but all of the tutorials are for C# and it seems there is none for PascalABC.NET. I don't know how to translate the code for C# to PascalABC.NET.

**Comment by ibond84** [comment]
Old pascal syntax
```
function MessageBox(h: integer; m,c: string; t: integer): integer;
  external 'User32.dll' name 'MessageBox';
...
MessageBox(0,'Hello!','Сообщение',0);
```

or
new syntax

```
type
  t1 = class
    [System.Runtime.InteropServices.DllImport('kernel32.dll')]
    class function Beep(a,b: integer): boolean; external;
  
  end;

begin 
  writeln(t1.Beep(200,400));
end.
```

**Comment by 3oheicrw** [comment]
> Old pascal syntax
> 
> ```
> function MessageBox(h: integer; m,c: string; t: integer): integer;
>   external 'User32.dll' name 'MessageBox';
> ...
> MessageBox(0,'Hello!','Сообщение',0);
> ```
> 
> or new syntax
> 
> ```
> type
>   t1 = class
>     [System.Runtime.InteropServices.DllImport('kernel32.dll')]
>     class function Beep(a,b: integer): boolean; external;
>   
>   end;
> 
> begin 
>   writeln(t1.Beep(200,400));
> end.
> ```

What about Type Marshaling and other advanced options of P/Invoke?

https://docs.microsoft.com/en-us/dotnet/standard/native-interop/type-marshaling

And what about calling conventions, too? How to specify calling convention? Like this?

https://www.freepascal.org/docs-html/ref/refsu73.html

I'm more about the .NET part of PascalABC.NET. I don't know Pascal.

**Comment by ibond84** [comment]
>What about Type Marshaling and other advanced options of P/Invoke?

You can use these attributes in pascal

>And what about calling conventions, too? How to specify calling convention? Like this?

```
    [System.Runtime.InteropServices.DllImport('msvcrt.dll', CharSet = System.Runtime.InteropServices.CharSet.Ansi, CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
    function printf(f: string; i: integer; s: string): integer; external;
  
begin
  printf('Print params: %i %s', 99, 'test');
end.
```

**Comment by 3oheicrw** [comment]
The syntax is very similar. So could this binding for free pascal be used with PascalABC.NET as is or with only little modifications?

https://github.com/ruanjiaxing/iup_pascal

https://github.com/ruanjiaxing/iup-fpc

Thanks.

**Comment by SunSerega** [comment]
Most methods will work almost as-is, but a lot of trouble comes with data types, which are more complex than `int`.

1. `PChar` wouldn't work to pass strings, because 1) it is a pointer to a 16-bit value, because .Net char contains Unicode symbol, and 2) passing `@s[1]`, where `s` is `string` would create a memory leak, as the string would be permanently blocked to suppress GC. But declaring parameter type as just `string` will cause default marshaller to take effect. And it converts the string to ANSI, so should work as-is. But it is, however, a one-directional marshaller. But receive `string` from unmanaged - you would need to `Marshal.AllocHGlobal` of right size and pass `IntPtr`. Then use `Marshal.PtrToStringAnsi` to convert to managed `string`. Though if function retuns string as a return value - `string` type works again.
2. Arrays of types other than `char` also have issues. Generally, the parameter declared as `ParType* par` in `C++` can be translated as 1) `par: ^ParType`, 2) `var par: ParType` and 3) `par: array of ParType`. Or it can also be 4) `par: ParType`, if in managed code `ParType` is declared as a formatted class, but that will cause marshaling overhead each time you pass the value of this class in and out of unmanaged code. Meanwhile, 1) option (and as long as `ParType` is a blittable `record` (`struct`), 2) and 3) options also) would not do any marshaling, passing address as-is.
3. The Last parameter of `IupLog` has an unmanaged type of `va_args`. There is no default marshaller in .Net for that. But it is certainly possible to implement the conversion. For PascalABC.Net I recommend something like this:
```
uses System;

// Preferably in a separate file, to properly incapsulate protected GetPtr
// And with every type except VaArg - in the implementation section
{$region VaArg}

type
  VaArg = abstract class
    
    protected function GetPtr: IntPtr; abstract;
    
    public static function operator implicit(x: integer): VaArg;
    public static function operator implicit(s: string): VaArg;
    
    public static function ProcessArgs(args: array of VaArg) := args.ConvertAll(arg->arg.GetPtr);
    
  end;
  
  VaArg_Int32 = sealed class(VaArg)
    private val: integer;
    public constructor(val: integer) := self.val := val;
    private constructor := raise new InvalidOperationException;
    
    // Idk if this is really how it is supposed to be,
    // I just found SO answer that did it, with author stating they also don't understand
    protected function GetPtr: IntPtr; override := new IntPtr(val);
    
  end;
  
  VaArg_StringANSI = sealed class(VaArg)
    private str_ptr: IntPtr;
    public constructor(s: string) := self.str_ptr :=
    System.Runtime.InteropServices.Marshal.StringToHGlobalAnsi(s);
    private constructor := raise new InvalidOperationException;
    
    protected function GetPtr: IntPtr; override := str_ptr;
    
    // Need to declare this, so that GC releases memory when deleting this object
    protected procedure Finalize; override :=
    System.Runtime.InteropServices.Marshal.FreeHGlobal(str_ptr);
    
  end;
  
static function VaArg.operator implicit(x: integer): VaArg := new VaArg_Int32(x);
static function VaArg.operator implicit(s: string): VaArg := new VaArg_StringANSI(s);

{$endregion VaArg}

procedure IupLog(&type: string; format: string; args: array of IntPtr);
external 'iup';

// Maybe also take "format" parameter into account:
// Take in {0}, {1}, etc. as in "string.Format", and then replace it with "%s", "%d", etc.
// before calling first overload of IupLog
procedure IupLog(&type: string; format: string; params args: array of VaArg);
begin
  
  // Default array marshler and then GC will take care of VaArg.ProcessArgs return value,
  // passing address of start of the array body as-is
  // Honestly using managed array is questionable here, because in essence,
  // we first create GC-managed object (the array), then immediately disable GC control over it (to pass it's body address)
  // Then, after IupLog call we enable GC control, only to delete it a moment later,
  // because it is a generation-0 object (I'm pretty sure it is)
  // Maybe using Marshal.AllocHGlobal to create unmanaged array would make more sense,
  // but then it needs to be deleted in `finally` block of `try`, and filling it would need much bigger code
  IupLog(&type, format, VaArg.ProcessArgs(args));
  
  // Do not call Finalize on args before this line
  // If IupLog is not inlined by JIT - this is not needed,
  // because the value of type "array of VaArg" is constructed before calling IupLog
  // and so lives outside it's call
  // But GC.KeepAlive is a nop after first JIT pass, so wouldn't hurt
  GC.KeepAlive(args);
  
end;

begin
  IupLog('INFO', 'num is %d, string is %s', 5, 'abc');
end.
```
