### ISSUE TITLE
English documents/tutorials of PascalABC.NET?

### ISSUE THREAD

**Issue by 3oheicrw** [pascalabcnet/pascalabcnet#2622]
I really interested in this language.

**Comment by retsyo** [comment]
chm can be opened as a compressed file by https://www.7-zip.org/download.html, then you can find many html files here. Decompress and merge html files into a large one.

For PDF, you can convert it into html too.

Then open the html in webbrowser and choose tool to translate the whole page into your language. 
Last step, you can copy the translated file into a doc/docx file. 

Above is what I have just done, however not into English.

there are some shortcomings
1. not everything is translated correctly
2. some code is translated
3. some code loses its format
4. it is difficult to put discrete htm files in proper order

I also found that PascalABC.NET is an interested language. However, it is tailered after pascal, I hope something modern can be introduced:
1. `begin-end` is annoying for writing. maybe this can be fixed by a more smart IDE, or be cancelled(by C#'s `{}`?)
2. `return` in `function`, else we have to add `exit`
```pascal
if a>0 then
    begin
        result := 0;
        exit; 
    end;
else result := 1;
```

**Comment by retsyo** [comment]
ok, I found https://www.deepl.com/ which can translate pdf/docx directly

**Comment by 3oheicrw** [comment]
I found this PDF suggested by someone on the FreeBASIC forum:

https://www.garychike.com/images2/PascalABCNet%20en-US.pdf

The forum thread is here: https://www.freebasic.net/forum/viewtopic.php?f=14&t=17058&start=915#p289031

**Comment by retsyo** [comment]
the pdf is the english version of PascalABCNET.chm

**Comment by 3oheicrw** [comment]
> the pdf is the english version of PascalABCNET.chm

Is there an English version of PascalABCNET.chm already available? Other than the one I posted? I can't find it. So far I only see the Russian version.

**Comment by retsyo** [comment]
no, I think there is no such a PascalABCNET.chm in English 

btw, [it is](http://pascalabc.net/en) said that `PascalABC.NET is a joint development of Russian and German programmers`, but I can't find any document in Germany.

**Comment by SunSerega** [comment]
> PascalABC.NET is a joint development of Russian and German programmers

Well yeah, a joint project of 2 devs: one Russian (miks1965), one German (ibond84). It's not like there is a separate office in Germany. And ibond usually doesn't touch documentation, he focuses on the deep backend.

I think there was someone on [forum](http://forum.mmcs.sfedu.ru/c/pascalabcnet/10), who said they will translate by first using google translator and then fixing the wrong translations. I was going to help if it went anywhere, but it didn't.

**Comment by miks1965** [comment]
We have sources of .chm in Github. Also we have some english translation of a help file made by non-professionals.

If you'll help to correct the translation wi'll organize & start this process.

Regardless of "small market" of PascalABC.NET the language is excellent, modern, is developed continiousely and can be used for many general-purpose tasks.

This is our proposal.

If not, I'll close the issue.

**Comment by 3oheicrw** [comment]
> We have sources of .chm in Github. Also we have some english translation of a help file made by non-professionals.
> 
> If you'll help to correct the translation wi'll organize & start this process.
> 
> Regardless of "small market" of PascalABC.NET the language is excellent, modern, is developed continiousely and can be used for many general-purpose tasks.
> 
> This is our proposal.
> 
> If not, I'll close the issue.

I'm not English speaker nor good at the language, too. I'm pleased with the English PDF suggested by the FreeBASIC forum member. Feel free to close this issue.
