### ISSUE TITLE
NullReferenceException in TreeConverter

### ISSUE THREAD

**Issue by BareGamer** [pascalabcnet/pascalabcnet#2698]
I have a huge fpc library file(several thousand lines of code) that I tried to compile. Just like last time I tried to do that, I crashed the compiler. Judging by my attempts to debug the issue, it is occurring somewhere in TreeConverter.CanNotConvertTypes(in the screenshot). However, I am not sure how to find the specific part of the pascal code that is causing the problem(because, well, there is a lot of code). Project attached.
![dnspy](https://user-images.githubusercontent.com/78811370/187769231-aeb3bb7f-cbd0-44ea-97b8-0b8884eb2d48.png)
[graphicsabc.zip](https://github.com/pascalabcnet/pascalabcnet/files/9464599/graphicsabc.zip)

**Comment by SunSerega** [comment]
Trying to debug compiler before finding minimal reproducible example of pascal code is a bad idea...

To find minimal code you just need to take a copy and start removing bits from it. And at least that unit isn't *that* interconnected, like some of mine.
Only better way is to automate it, and I have a program for that with a (still) half-baked parse but... It also crashes when I feed it this code. Oh well, I shouldn't touch it now, at midnight...

Meanwhile, can you describe, why would you need to compile fpc unit in .Net language? There are soooo many things I can see which make it easier to rewrite from scratch, then making it work. Pointers and character encodings, to name a few.

**Comment by BareGamer** [comment]
Well, first of all I was curious how easily you could adapt fpc code to PascalABC.NET. And second of all, I couldn't really understand how to use NET vulkan bindings with ABC, plus they seemed a bit too C#-specific to me. I think I tried to compile Silk, but instead I first had to download some build system and then the code decided after 20 minutes of compiling that it wants to error out. So I had again thought that porting it from a somewhat syntactically-similar language would just be easier.

> Meanwhile, can you describe, why would you need to compile fpc unit in .Net language? There are soooo many things I can see which make it easier to rewrite from scratch, then making it work. Pointers and character encodings, to name a few.

Could you elaborate on that a bit? I suspect you mean that ABC uses unicode-16, but otherwise not much ideas. One part that really is a bit of a cornerstone is FillChar. Not sure how I could possibly replace it.

**Comment by SunSerega** [comment]
> I suspect you mean that ABC uses unicode-16

Yes, you'll need things from `System.Runtime.InteropServices` to feed text and other managed things to unmanaged DLL and back, unless you make use of default marshaling that comes with `external` (syntax for `DllImport` from C#).

You might not be able to use `external` if Vulkan works like OpenGL - where you might get different function pointers for different contexts (IDK, haven't touched Vulkan yet). Then you need to dynamically load the DLL, as you already do. But it will look much different in this pascal.

And as to pointers... Well, it's the whole thing. In .Net it's expected to only be used by those familiar with how CLR works under the hood, so this pascal doesn't even stop you from doing some easy dumb things, like pointers to an array element. And the cushioning it does provide for such wrong cases - *might* turn access violation into a memory leak, but nothing better.

> I couldn't really understand how to use NET vulkan bindings with ABC

Use `$reference` to bind DLL to your program.
Then `uses` the namespaces if you don't want to type out full names. Or make synonyms for separate types.
But yeah, the code using managed DLL will work almost like a mirror to C# examples, with a few differences, like `:=` instead of `=`.

---

Do you need specifically Vulkan? I'm the maintainer of the `OpenGL` and `OpenCL` units, so I can help with them.
There are still many things I want to improve, especially in high-level stuff, but the low-level units, akin to your `Vulkan.pas`, are pretty stable on windows and soon (TM) will work on Linux with mono.

**Comment by BareGamer** [comment]
I don’t really need vulkan specifically, just thought that learning about it wouldn’t really be a bad idea. As of the pointers thing, I’m pretty sure you can do a lot of dangerous things with pointers. Why is getting a pointer to an array element dangerous though?
I saw you OpenGL unit and a lot of marshaling going on there. I don’t really remember if you did anything related to strings though. Btw, I had this weird bug when I just included opengl and the program refused to compile and also crashed the ide. But that version was a year old, maybe it works now.

**Comment by SunSerega** [comment]
> just thought that learning about it wouldn’t really be a bad idea

Yeah, it's more modern, and I want to make a unit for it too, but I noticed it much later and there isn't anything not replaceable by OpenGL or OpenCL, so low priority for now.

> I’m pretty sure you can do a lot of dangerous things with pointers

Of course, and I do, but it's hard to start using them properly, because of many technicalities.

> Why is getting a pointer to an array element dangerous though?

Awful oversimplification: Because it's a class, and their memory is managed by GC. GC is responsible but also allowed to do whatever it wants to optimize memory usage, like randomly moving objects around in RAM.

> Why not just keep them managed

*Managed* is referring to "managed by CLR", including GC. C/C++ libraries like OpenGL and Vulkan are not managed by them.

And yeah, again, string encodings, as well as, for instance, sizes of `boolean` (it is undefined in .Net and 4 bytes by default in `external` because WinAPI)

But a good marshaler wouldn't reallocate memory for everything. For instance, in the case of arrays, it is mostly possible to lock them in place. Even if they are arrays of generic type (but CLR needs to be fooled to not freak out).

> I saw you OpenGL unit and a lot of marshaling going on there

I took control of many types of marshaling. Partially because in OpenGL I need dynamic loading, incompatible with `external`. But also for obscure optimizations and a few nice things, like generic arrays.

> I don’t really remember if you did anything related to strings though

There are more cases with strings in OpenCL. But if you want examples - code for function definitions is generated, and I have tests for the generators.

1. Input of the tests[<sup>[1]</sup>](https://github.com/SunSerega/POCGL/blob/stable/Packing/Template/FuncVirtualTest.dat)
2. Most important for you log[<sup>[2]</sup>](https://github.com/SunSerega/POCGL/blob/stable/Packing/Template/Log/FinalFuncOverloads.log)
3. Outputs[<sup>[3]</sup>](https://github.com/SunSerega/POCGL/blob/stable/Packing/Template/Log/FuncVirtualTest.template)[<sup>[4]</sup>](https://github.com/SunSerega/POCGL/blob/stable/Packing/Template/Log/FuncVirtualTest.Implementation.template)

> program refused to compile and also crashed the ide

The compiler is launched as a separate process. If IDE crashes - it's something separate.

**Comment by SunSerega** [comment]
Ok, fixed my program for automating MRE (it was trying to read definition of `VK_API_VERSION` as if it's an enum).
Here is minimal code:
```
type
  enum1 = (
    v1 = 1,
    v2 = v1
  );
  
begin end.
```
In your case this was `VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR`.

**Comment by BareGamer** [comment]
Well. Looks like that’s the second enum bug in the compiler in 2 days. Would such an assignment be valid in PascalABC after the bug is fixed though? As far as I understand, that was done to alias Nvidia raytracing extensions to Khronos ones to simplify porting from earlier nv-only RT code.

**Comment by SunSerega** [comment]
Standard enums are very basic, and so are used in very basic cases. And bugs you found are found in obscure cases, not found by anyone until now. And yes, these cases probably would most probably work after fixes.

Meanwhile, something like `enum class` from C++ is only planned and I don't like namespace pollution of standard enums, so I generate [stuff like that](https://github.com/SunSerega/POCGL/blob/stable/Packing/Template/OpenGL/Groups.template) instead.

And you should generate code for enums and methods anyway, to use [this](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/xml/vk.xml) file instead of writing them by hand. Otherwise, bindings are hard to update and prone to human errors.

**Comment by BareGamer** [comment]
Oh, I haven’t thought you could deal with enums like that. 
About the xml: this Vulkan.pas file is actually generated by a parser, but it is for fpc/Delphi. I tried to patch it somehow to make the it compilable in PascalABC as the third language, but found the sizeof class compiler crash. You then told me that the program is too fpc-specific, so I gave up on it. Maybe I should try to make slight modifications for it to only generate PascalABC.

**Comment by miks1965** [comment]
Если не будет приведен минимальный код, мы Issue закроем

**Comment by SunSerega** [comment]
А я что сделал? В треде <10 сообщений и паскалевский код всего один...

**Comment by miks1965** [comment]
Да нет, Вы ни при чём. Просто Issue надо закрывать.

**Comment by SunSerega** [comment]
> Да нет, Вы ни при чём.

Я имел в виду что уже привёл его.

Но вы её не исправили и не удосужились <10 сообщений прочитать.

**Comment by SunSerega** [comment]
#2705
