### ISSUE TITLE
Nuget support is broken

### ISSUE THREAD

**Issue by 3oheicrw-ver2** [pascalabcnet/pascalabcnet#2926]
I want to install https://github.com/picoe/Eto. I entered this URL:

https://www.nuget.org/packages/Eto.Forms

I click Install package and it shows Unhandled exception has occurred. If I click Quit, the IDE crashed.

**Comment by 3oheicrw-ver2** [comment]
@SunSerega Any pointers? I'm new to Nuget, too. This is the first experience of me with it. So, it could be I'm using it wrong.

**Comment by SunSerega** [comment]
IDK, I don't use projects, let alone their Nuget feature. For the few occasions I used 3rd party libraries in Pascal - I downloaded them manually. You can click "Download package" on the page you link and then use 7Zip to open it.

Well, the Nuget wrap for projects still shouldn't crash, so this issue is valid. It's just that there is no one to actually fix it.

The efforts lately focus more on #2912. That same person already made `PascalABC.NET SDK`, and you can already use it... But only from the console.
I also have 0 experience with that SDK, I'm waiting for IDE integration for it.

**Comment by 3oheicrw-ver2** [comment]
It's just the UI that sucks. People will expect it's an URL. The fact it's not. It's a nuget command, except nuget itself.

To install Eto, put this into the text box: `Eto.Forms -Version 2.8.0`

**Comment by 3oheicrw-ver2** [comment]
https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-nuget-cli
