### ISSUE TITLE
GraphABC doesn't redraw with window resize

### ISSUE THREAD

**Issue by ghost** [pascalabcnet/pascalabcnet#2927]
When you resize the window or simply click to maximize it, the graph is still in it initial size and not scaled to meet the new window size. This means the graph is not redraw.

**Comment by SunSerega** [comment]
You are using the wrong tool. In `GraphABC` you describe how to draw every frame, in `ABCObjects` you place objects that are then drawn during every frame.

Also, these units are old and only preferred if you want them to work in Linux. There are more modern units: `GraphWPF` and `WPFObjects`. For instance, in `GraphWPF` you draw a graph on every frame like this:
```
## uses GraphWPF;

BeginFrameBasedAnimation(()->
begin
  DrawGraph(Sin);
end);
```
Besides that, there is a special unit just for plots:
```
## uses PlotWPF;

new LineGraphWPF(-5,+5, Sin);
```
This one you can even move with your mouse. Tho, the points are only placed at the beginning, so it cuts off outside the original viewport.

**Comment by 3oheicrw-ver2** [comment]
> This one you can even move with your mouse. Tho, the points are only placed at the beginning, so it cuts off outside the original viewport.

How to have it draw the graph wherever I move my mouse? Like Desmos and Geogebra.

**Comment by SunSerega** [comment]
I'd implement it myself in `GraphWPF`. Make own controls and then change passed in `X` and resulting `Y` of a function, based on shift and scaling.

**Comment by 3oheicrw-ver2** [comment]
> I'd implement it myself in `GraphWPF`. Make own controls and then change passed in `X` and resulting `Y` of a function, based on shift and scaling.

Where to download and how to use?

**Comment by SunSerega** [comment]
`GraphWPF` is already installed with the latest version of PascalABC.Net
And if you are asking about the idea I described - read carefully, I said `I'd`, which means `I would` (if I were in your position).
Myself - I implemented stuff like that using OpenGL a couple of times, but I don't have those codes on hand. Also, it wasn't for graphs, it was for some specific shapes.
P.S. Well, there is some example code I made for my OpenGL unit in `PABCWork.NET\Samples\StandardUnits\OpenGL и OpenCL\OpenGLABC\Точки на поле`. But it would hardly help you, since the actual translate/scale logic is implemented per-point in a shader, rather than by changing the input and output of a function.

**Comment by SunSerega** [comment]
Just do the math yourself...

**Comment by 3oheicrw-ver2** [comment]
How to plot arbitrary function? I noticed the function doesn't have the variable. So, for example, instead of Sin(x), I want to plot Sin(2x). How could I do that?

**Comment by SunSerega** [comment]
Just define it:
```
## uses GraphWPF;

function my_func(x: real) :=
  Sin(2*x);

BeginFrameBasedAnimation(()->
begin
  DrawGraph(my_func);
end);
```
Or, you can use another lambda (anonymous/nameless) function:
```
## uses GraphWPF;

BeginFrameBasedAnimation(()->
begin
  DrawGraph(x->Sin(2*x));
end);
```

**Comment by 3oheicrw-ver2** [comment]
Can I use the same trick with `LineGraphWPF`?

**Comment by SunSerega** [comment]
Yes, lamdas (one of the ways to define a function) and delegates (functions stored in variables) are language features, they don't depend on any unit.
