### ISSUE TITLE
bug in sequence index or foreach?

### ISSUE THREAD

**Issue by retsyo** [pascalabcnet/pascalabcnet#3235]
I am using pascalabc.net 3.10.2

# 1. the correct code
the code
```pascal
## 
Randomize(2024);
var intPDF := arrrandomInteger(8);

Println('intPDF = ', intPDF);

var floatPDF := intPDF.Select(x -> x / intPDF.Sum);
Println('floatPDF ', floatPDF);
Println('floatPDF.sum =', floatPDF.sum);
println;

//intPDF := floatPDF.Select(x->round(x*100));
foreach var x in floatPdf index idx do
begin
//  intPDF[idx] := floor(x * 100);
  println(idx, '  ', x, '  ', floor(x * 100));
end;
```
prints
```
intPDF =  [11,70,52,57,1,33,78,85]
floatPDF  [0.0284237726098191,0.180878552971576,0.134366925064599,0.147286821705426,0.00258397932816537,0.0852713178294574,0.201550387596899,0.219638242894057]
floatPDF.sum = 1

0    0.0284237726098191    2
1    0.180878552971576    18
2    0.134366925064599    13
3    0.147286821705426    14
4    0.00258397932816537    0
5    0.0852713178294574    8
6    0.201550387596899    20
7    0.219638242894057    21

```
as we can find that the `foreach` finds out corrected value in `floatPDF`

# 2. the wrong value
however, if I change the code to
```pascal
## 
Randomize(2024);
var intPDF := arrrandomInteger(8);

Println('intPDF = ', intPDF);

var floatPDF := intPDF.Select(x -> x / intPDF.Sum);
Println('floatPDF ', floatPDF);
Println('floatPDF.sum =', floatPDF.sum);
println;

//intPDF := floatPDF.Select(x->round(x*100));
foreach var x in floatPdf index idx do
begin
  intPDF[idx] := floor(x * 100);
  println(idx, '  ', x, '  ', floor(x * 100));
end;
```
we can find that 
```
intPDF =  [11,70,52,57,1,33,78,85]
floatPDF  [0.0284237726098191,0.180878552971576,0.134366925064599,0.147286821705426,0.00258397932816537,0.0852713178294574,0.201550387596899,0.219638242894057]
floatPDF.sum = 1

0    0.0284237726098191    2
1    0.185185185185185    18
2    0.159509202453988    15
3    0.197231833910035    19
4    0.00398406374501992    0
5    0.132    13
6    0.339130434782609    33
7    0.459459459459459    45
```
that is `foreach` does not get right x from `floatPdf`. Why?

**Comment by SunSerega** [comment]
The problem isn't `foreach`. The problem is using functions and just hoping they work somehow rather than understanding and deliberately choosing an approach.

The most basic idea in LINQ is lazily computed sequences. When you call `.Select`, you are not creating a new collection containing results - you are creating a new object containing reference to the source (`intPDF`) and the algorithm (`x -> x / intPDF.Sum`).
That way, you don't need memory to store the result because every next item is computed right before the next iteration of `foreach` starts.
But you need to understand what is happening to anticipate what behavior to expect.
For instance, when you try to use the results (like in `Print`), you recalculate the whole sequence.
Or like in the case you found, you are changing the input array, which changes the result on the next iteration.

When you want to turn the stored algorithm into a collection, you call methods like `.ToArray`, `.ToList`, `.ToHashSet`, etc., based on how you'd be using the resulting collection and what properties you need for that. This is an example of what I mean by "deliberately choosing".
Yes, this requires using your head more than similar methods on scripts like JS or Python, but in exchange, you get much faster code and much fewer chances to cook some legacy code instant-noodle style.

Similarly, you wouldn't see the issue in this code if you weren't recomputing the `.Sum` for every since item.
There isn't any kind of lambda translator that could decide that `intPDF.Sum` is constant, separate it out for you, and compute it once instead of on every iteration.
It wouldn't just be auto-magical (which is bad for the deliberate approach); it would also be wrong in this case because `intPDF.Sum` is, in fact, not a constant. You're changing it on every iteration of the `foreach`.
