### ISSUE TITLE
Programming Taskbook. Задание Array3. Неверное решение в "примере верного решения"

### ISSUE THREAD

**Issue by NZainchkovskiy** [pascalabcnet/pascalabcnet#675]
В прилагающемся к среде разработки задачнике допущены ошибки в примере верного решения.
![pascalabc](https://user-images.githubusercontent.com/19357901/35907153-226d58a6-0bfe-11e8-9092-af8b244dd09b.png)

Код
```
const 
    NumberOfDigits = 8;
    A = -1.95;
    D = 1.89;
var apItems := SeqGen(NumberOfDigits, A, number -> number + D);
Println(apItems);
```
Выводит следующие значения:

> [-1.95,-0.0600000000000001,1.83,3.72,5.61,7.5,9.39,11.28] 

Правильность значений можно математически проверить. Сомнение вызывает только непонятно откуда взявшаяся 0.0000000000000001 во втором элементе, но это уже скорее вопрос к функции SeqGen или к логике сложения Real чисел.

Поправьте, пожалуйста, задачник, иначе это может сбивать с толку учеников.
Спасибо!

**Comment by miks1965** [comment]
В задачнике всё верно. Отображаются вещественные числа до второго знака, а на самом деле в третьем знаке там не нули - потому и расхождение. Задачник вычисления с вещественными всё равно проверяет с некоторой точностью

**Comment by NZainchkovskiy** [comment]
С точки зрения программирования, видимо, всё верно. Но как Вы думаете, как это с точки зрения UX? Вы даёте ученикам входные данные, округленные до сотых, а сами считаете ответ, используя больше знаков после запятой! Как ученику догадаться, что когда ему говорят, что A = -1.95, то на самом деле там ещё там дальше есть знаки? Попробуйте сами решить эту задачу, пользуясь данными с экрана, и получить "верное решение", отображаемое на экране. Это невозможно! Так что проблема всё-таки есть. Как вариант - нужно при ввчислении решения округлять числа до того же знака, до которого идёт округление в интерфейсе.

**Comment by m-abramyan** [comment]
Мы не даем ученикам данные, округленные до сотых. На экране просто отображаются округленные значения исходных данных.Вещественные данные всегда генерируются с помощью датчика случайных чисел, поэтому в них обязательно будут больше значащих разрядов, чем отображено на экране.Однако программа ученика всегда получает правильные данные без всякого округления (это можно проверить, если вывести эти данные в разделе отладки функцией Show, предварительно установив большую разрядность процедурой SetPrecision). Ученик должен понимать, что вещественные числа всегда отображаются на экране с некоторой точностью и что фактические их значения могут отличаться от выведенных на экране (в следующих дробных знаках, а также с учетом округления).Итак, при работе с вещественными числами следует четко понимать, что данные, отображаемые на экране, - это округленные значения фактических данных(как исходных, так и результирующих), и не пытаться проверить правильность предложенного решения, вводя в точности те числа, которые указаны на экране.В следующей версии задачника соответствующее пояснение будет добавлено к справочной информации, отображаемой в окне задачника при нажатии клавиши F1.   -- С уважением,М. Абрамянmailto:mabr@math.sfedu.ru   08.02.2018, 09:54, "Nikolay Zainchkovskiy" <notifications@github.com>:С точки зрения программирования, видимо, всё верно. Но как Вы думаете, как это с точки зрения UX? Вы даёте ученикам входные данные, округленные до сотых, а сами считаете ответ, используя больше знаков после запятой! Как ученику догадаться, что когда ему говорят, что A = -1.95, то на самом деле там ещё там дальше есть знаки? Попробуйте сами решить эту задачу, пользуясь данными с экрана, и получить "верное решение", отображаемое на экране. Это невозможно! Так что проблема всё-таки есть. Как вариант - нужно при ввчислении решения округлять числа до того же знака, до которого идёт округление в интерфейсе.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by NZainchkovskiy** [comment]
Я понимаю, что не могу вас учить как писать программы, но с точки зрения пользовательского опыта это ужасное решение, которое легко исправить. Поведение программы должно быть предсказуемо для пользователя. Пользователь не должен догадываться, что программа что-то скрывает от него. Учитывая, что в задачнике нет очевидного способа отключить округление, чтобы увидеть вещественное число с большей точностью. Ученикам и так может быть сложно решать задачу (собственно, в этом и смысл), а когда у него в голове не складывается элементарная математика - это может ещё больше запутать. Что мешает после генерации случайного числа его округлять до двух знаков, чтобы исключить данную путаницу? Мне кажется, для академических целей это будет гораздо полезнее, чем добавление пояснения в справку. Мне кажется, что обучая детей программированию нужно служить некого рода примером для них. А то, как ведет задачник сейчас в таких ситуациях, это, извините, плохой пример.
Никого не хотел обидеть и спасибо за Ваш труд!

**Comment by m-abramyan** [comment]
Спасибо за конструктивную критику. Мы постараемся в следующих версиях задачника откорректировать те задания, в которых проявляется отмеченный Вами недочет (собственно, таких заданий немного: только те, в которых над вещественными числами выполняются арифметические операции, причем несложные, для которыхрасхождение с ожидаемым результатом можно увидеть "невооруженным глазом"). Между прочим, в некоторых заданиях группы Begin такая корректировка уже сделана(после аналогичной критики). Можете написать непосредственно мне (m-abramyan@yandex.ru), для каких заданий групп Array и Matrix (и других) это желательно сделать.  -- С уважением,М. Абрамянmailto:mabr@math.sfedu.ru   08.02.2018, 11:56, "Nikolay Zainchkovskiy" <notifications@github.com>:Я понимаю, что не могу вас учить как писать программы, но с точки зрения пользовательского опыта это ужасное решение, которое легко исправить. Поведение программы должно быть предсказуемо для пользователя. Пользователь не должен догадываться, что программа что-то скрывает от него. Учитывая, что в задачнике нет очевидного способа отключить округление, чтобы увидеть вещественное число с большей точностью. Ученикам и так может быть сложно решать задачу (собственно, в этом и смысл), а когда у него в голове не складывается элементарная математика - это может ещё больше запутать. Что мешает после генерации случайного числа его округлять до двух знаков, чтобы исключить данную путаницу? Мне кажется, для академических целей это будет гораздо полезнее, чем добавление пояснения в справку. Мне кажется, что обучая детей программированию нужно служить некого рода примером для них. А то, как ведет задачник сейчас в таких ситуациях, это, извините, плохой пример.Никого не хотел обидеть и спасибо за Ваш труд!—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
